In [2]:
import numpy as np
from numpy.matrixlib.defmatrix import matrix


In [5]:
lista_py = [1, 2, 3, 4]
lista_py * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [7]:
array_np = np.array([1, 2, 3, 4])
array_np * 2

array([2, 4, 6, 8])

In [16]:
array_zeros = np.zeros(1000)
print(array_zeros)
len(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

1000

In [19]:
array_nums = np.ones(1000)
array_nums

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [28]:
array_seq = np.arange(1000)
array_seq

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [52]:
matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [54]:
matriz_unos = np.ones((4,5))
print(matriz_unos)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [65]:
space1 = np.linspace(0,100,50)
space1

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [66]:
# Creamos un array de ejemplo de 3 filas y 4 columnas
mi_matriz = np.arange(12).reshape(3, 4)

# Ahora, lo inspeccionamos
print("La matriz es:")
print(mi_matriz)
print("-----------")
print("Forma (shape):", mi_matriz.shape)
print("Número de dimensiones (ndim):", mi_matriz.ndim)
print("Tipo de dato (dtype):", mi_matriz.dtype)

La matriz es:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------
Forma (shape): (3, 4)
Número de dimensiones (ndim): 2
Tipo de dato (dtype): int64


In [67]:
mi_array_misterioso = np.linspace(0, 10, 24).reshape(2, 3, 4)

print("Shape:", mi_array_misterioso.shape)
print("ndim:", mi_array_misterioso.ndim)
print("dtype:", mi_array_misterioso.dtype)
print("-----------")
print(mi_array_misterioso)

Shape: (2, 3, 4)
ndim: 3
dtype: float64
-----------
[[[ 0.          0.43478261  0.86956522  1.30434783]
  [ 1.73913043  2.17391304  2.60869565  3.04347826]
  [ 3.47826087  3.91304348  4.34782609  4.7826087 ]]

 [[ 5.2173913   5.65217391  6.08695652  6.52173913]
  [ 6.95652174  7.39130435  7.82608696  8.26086957]
  [ 8.69565217  9.13043478  9.56521739 10.        ]]]


In [73]:
mi_vector = np.array([10, 20, 30, 40, 50])
print(f'primer elemento: {mi_vector[0]}')
print(f'ultimo elemento: {mi_vector[-1]}')


primer elemento: 10
ultimo elemento: 50


In [109]:
mi_matriz = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
print(f'El ocho está: {mi_matriz[2, 1]}')
print(f'{mi_matriz[0:1]}')
var = mi_matriz[0, :]
var = mi_matriz[:, 1]
mi_matriz[1:, 1:]

El ocho está: 8
[[1 2 3]]


array([[5, 6],
       [8, 9]])

In [129]:
mi_matriz = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
mi_matriz[mi_matriz > 5]

mi_matriz[(mi_matriz > 2) & (mi_matriz < 8)]

array([3, 4, 5, 6, 7])

In [3]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

c = a - b
print(c)

[ 9 18 27 36]


In [10]:

e = np.sum(a*b)
print(e)
producto_scalar = np.dot(a, b)
print(producto_scalar)
producto_scalar_v2 = a @ b
print(producto_scalar_v2)

300
300
300


In [27]:
datos = np.arange(1, 13).reshape(3, 4)
print(datos)
print(np.max(datos))
print(datos.sum(axis=0))
#add 100 to data.
data100 = datos + 100
print(data100)
modificadores = np.array([100, 200, 300, 400])
sum_mod = datos + modificadores
print(sum_mod)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[15 18 21 24]
[[101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]
[[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]]
